---
- name: A play that runs on the ansible host
  hosts: "{{ ansible_target }}"
  #hosts: localhost
  vars_files:
    - vars.yml
    - private.yml

  roles:
    - { role: base, become: true, tags: ['base'] }
    - { role: fits, become: true, tags: ['fits'] }
    - { role: hyrax-dev, tags: ['hyrax'] }
    - { role: redis, become: true }
