---
- name: A play that runs on the ansible host
  hosts: "{{ ansible_target }}"
  #hosts: localhost
  vars_files:
    - vars.yml
    - private.yml

  roles:
    - { role: fits, become: yes }
    - { role: hyrax-dev }
    - { role: redis, become: yes }
    #- { role: ffmpeg, tags: ffmpeg }
