---
- name: Build a fullstack instance of fedora/samvera/hyrax
  hosts: "{{ ansible_target }}"
  #hosts: localhost
  vars_files:
    - vars-full.yml
    - private.yml

  roles:
    - { role: base, become: true, tags: ['base'] }
    - { role: fits, become: true, tags: ['fits'] }
    - { role: hyrax-fullstack, become: true, tags: ['hyrax'] }
    - { role: postgresql, become: true, tags: ['postgres'] }
    - { role: redis, become: true }
    - { role: fedora, become: true, tags: ['fedora'] }
    - { role: solr, become: true, tags: ['solr'] }
    - { role: apache, become: true, tags: ['apache'] }
