---
- name: Build a fullstack instance of fedora/samvera/hyrax
  hosts: "{{ ansible_target }}"
  #hosts: localhost
  vars_files:
    - vars-full.yml
    - private.yml

  roles:
    - { role: fits, become: yes }
    - { role: hyrax-fullstack, become: yes }
    - { role: postgresql, become: yes, tags: ['postgres'] }
    - { role: redis, become: yes }
    - { role: fedora, become: yes, tags: ['fedora'] }
    #- { role: solr, tags: ['solr'] }
    #- { role: apache, tags: ['apache'] }
