---
- name: install tomcat packages
  yum: name={{ item }} state=present
  with_items:
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps

- name: set tomcat to restart on reboot
  service: name=tomcat enabled=yes

- name: stop tomcat
  service:
    name: tomcat
    state: stopped

- name: create fedora data dir
  file:
    path: '{{ item }}'
    owner: '{{ fedora_user }}'
    group: '{{ fedora_group }}'
    mode: 0770
    state: directory
  with_items:
    - "{{ fedora_data_dir }}"

- name: download fedora repository
  get_url: 
    url: https://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/{{ fedora_version }}/fcrepo-webapp-{{ fedora_version }}.war
    dest: "{{ fedora_app_dir }}/fedora.war"
    owner: '{{ fedora_user }}'
    group: '{{ fedora_group }}'
    mode: 0444
    timeout: 100

- name: add fedora and java config options to tomcat.conf
  template: src=tomcat.conf.j2 dest=/etc/tomcat/tomcat.conf

- name: change fedora.yml prod port to 8080
  replace:
    dest: "{{ application_home }}/config/fedora.yml"
    regexp: '127\.0\.0\.1:8983\/fedora\/rest'
    replace: '127.0.0.1:8080/fedora/rest'

- name: restart tomcat
  service: name=tomcat enabled=yes state=restarted
