tcdev_name: localhost
tcdev_port: 8983
tcprod_name: localhost
tcprod_port: 8080
solr_collection: druw
devdb_name: db/development.sqlite3
proddb_name: db/production.sqlite3
testdb_name: db/test.sqlite3
