---
  - name: devise.rb
    lineinfile:
      #path: /var/sufia/config/initializers/devise.rb'
      dest: "{{ application_home }}/config/initializers/devise.rb"
      regexp: '^  # config.secret_key'
      line: "  config.secret_key = '{{ devise_secret }}'"
      backrefs: yes

  - name: Add default secret to secrets.yml
    lineinfile:
      dest: "{{ application_home }}/config/secrets.yml"
      state: present
      regexp: '<%= ENV\["SECRET_KEY_BASE"\] %>'
      line: "{{ rails_secret }}"
      backrefs: yes

  - name: Add default roles to config/role_map.yml
    become: yes
    blockinfile:
      dest: "{{ application_home }}/config/role_map.yml"
      insertafter: '  # Add roles for users here.'
      content: |2
          admin_policy_object_editor:
            - archivist1@example.com
          researcher:
            - archivist1@example.com
            - researcher1@example.com

  #- name: tinymce-rails-imageupload kludge
  #  lineinfile:
  #    dest: "{{ application_home }}/config/application.rb"
  #    insertbefore: "^  end"
  #    line: "    config.tinymce.install = :copy"

