---
- name: install ffmpeg build dependencies
  become: yes
  yum: pkg={{ item }} state=latest
  with_items:
    - autoconf
    - automake
    - cmake
    - freetype-devel
    - gcc
    - gcc-c++
    - git
    - libtool
    - make
    - mercurial
    - nasm
    - pkgconfig
    - yasm
    - zlib-devel

- name: install ffmpeg
  command: sh roles/ffmpeg/files/ffmpeg-centos7.sh
