---
  - name: Install sufia dependencies
    become: yes
    yum: pkg={{ item }} state=latest
    with_items:
      - clamav
      - coreutils
      - gcc-c++
      - git
      - GraphicsMagick
      - ImageMagick-devel
      - libreoffice-headless
      - libreoffice
      - nodejs
      - poppler-utils
      - sqlite-devel

  - name: install ruby
    become: true
    yum: name=https://github.com/feedforce/ruby-rpm/releases/download/{{ ruby_version }}/ruby-{{ ruby_version }}-1.el7.centos.x86_64.rpm

  - name: install rails
    become: true
    gem: name=rails version="{{ rails_version }}" user_install=no

  - name: Check if Rails app exists.
    stat: "path={{ application_home }}"
    register: rails_app

  - name: Create new rails app
    shell: "rails new {{ application_home }} -m https://raw.githubusercontent.com/projecthydra/sufia/master/template.rb creates={{ application_home }}/Gemfile"
    when: rails_app.stat.exists == false

  - name: Generate primary work type
    command: "bundle exec rails generate sufia:work Work chdir={{ application_home }} creates={{ application_home }}/spec/models/work_spec.rb"

  - name: whitelist the 10.0.2.2 network space in the Web Console config
    tags: whitelist
    blockinfile:
      dest: "{{ application_home }}/config/environments/development.rb"
      insertbefore: "end"
      block: |2
          class Application < Rails::Application
            config.web_console.whitelisted_ips = '10.0.2.2'
          end
