---
- name: install git
  sudo: true
  yum: name=git state=present

#- name: git checkout druw
#  git:
#    repo={{ application_repo }}
#    dest={{ application_home }}
#    accept_hostkey=true
#    version=master
#    update=no

- name: install ruby
  sudo: true
  yum: name=https://github.com/feedforce/ruby-rpm/releases/download/2.3.0/ruby-2.3.0-1.el7.centos.x86_64.rpm

- name: install rails
  sudo: true
  gem: name=rails state=latest user_install=no

- name: Check if Rails app exists.
  stat: "path={{ application_home }}"
  register: rails_app

- name: Create new rails app
  shell: "rails new {{ application_home }} chdir=~/sync creates={{ application_home }}/Gemfile"
  when: rails_app.stat.exists == false

- name: Copy Gemfile
  template: src=Gemfile.j2 dest="{{ application_home }}/Gemfile"

#- name: Install gems from Gemfile
#  bundler: state=present chdir={{ application_home }} gemfile="{{ application_home }}/Gemfile"

- name: Bundle install
  command: "bundle install --path vendor/bundle chdir={{ application_home }} creates={{ application_home }}/vendor/bundle"

- name: Initial sufia install
  command: "rails generate sufia:install -f chdir={{ application_home }}"
